### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Charlie-robin** [PabloJulianRial/calculator-waiheke#2]
# Feedback

## Requirements

- Deployed website
- Github Repo:
  - README.md
  - 15 commits
- Be responsive and built mobile-first, it should work on different screen widths
- Accept a minimum of 2 inputs, perform an operation and return the output.
- DO NOT USE `eval()`
- Code is highly readable (good naming and indented correctly)

### Let's Build

- A working Calculator
- Practice using Git and GitHub flow
- Apply what you are learning.
  - SCSS
  - BEM

## Score

[MARKING-SCHEME](https://github.com/nology-tech/Waiheke-Course-Resources/blob/main/student-resources/02-javascript-typescript/calculator-marking-scheme.md)

| Category             | Score    |
| -------------------- | -------- |
| Version Control      | 10 / 10  |
| Site Output          | 35 / 45  |
| Readability          | 15 / 20  |
| Responsiveness       | 10 / 10  |
| Code Knowledge & Use | 15 / 25  |
| Total Score          | 85 / 110 |

#### Positive

- I like that you are keeping the ball rolling with the topics we covered in the first week. Keep on using media queries, grid and flex!

  - I have given you some pointers for SCSS & BEM below.

- I like that you went and researched and implemented CSS animations on your own.
  - I keep a list of small topics I am interested in and when I hit a blocker I go have a look at them.

#### Constructive

- Your BEM is a little off, I am going to refactor your code so you have an example of how it should be structured.
  - It is lowercase hyphenated for the name if it is two words `clearEntry -> clear-entry`
  - Use modifiers if elements are slightly different, you do not want to have `block__element__element` like `display__text__second`

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="./src/style.scss" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@400..900&" rel="stylesheet" />
    <title>Vite + TS</title>
  </head>
  <body>
    <!-- EVERY ELEMENT THAT GETS STYLED GETS A CLASS -->
    <h1 class="title">Space Calculator</h1>
    <!-- calculator IS THE MAIN BLOCK ELEMENT -->
    <div class="calculator">
      <!-- ITEMS INSIDE IT ARE ITS ELEMENTS -->
      <div class="calculator__display">
        <!-- IF YOU NEED ONE TO BE SLIGHTLY DIFFERENT ADD A MODIFIER -->
        <input
          class="calculator__display-text calculator__display-text--second"
          readonly
          id="input2"
          autocomplete="off"
        />
        <input class="calculator__display-text" readonly id="input1" maxlength="9" autocomplete="off" />
      </div>
      <div class="calculator__buttons-container">
        <div class="calculator__primary-buttons">
          <!-- I MADE BUTTON A BLOCK AS YOU HAVE A LOT OF MODIFIERS -->
          <button class="button button--grey button--clear">C</button>
          <button class="button button--grey button--clear-entry">⌫</button>
          <button class="button button--grey button--percent">%</button>
          <button class="button button--orange button--divide button--operator button--to-disable">÷</button>
          <button class="button button--number">7</button>
          <button class="button button--number">8</button>
          <button class="button button--number">9</button>
          <button class="button button--orange button--times button--operator button--to-disable">×</button>
          <button class="button button--number">4</button>
          <button class="button button--number">5</button>
          <button class="button button--number">6</button>
          <button class="button button--orange button--minus button--operator button--to-disable">-</button>
          <button class="button button--number">1</button>
          <button class="button button--number">2</button>
          <button class="button button--number">3</button>
          <button class="button button--orange button--plus button--operator button--to-disable">+</button>
          <button class="button button--number button--double-zero">0</button>
          <button class="button button--number button--decimal">.</button>
          <button class="button button--orange button--equals">=</button>
        </div>
        <div class="calculator__secondary-buttons">
          <button class="button button--extra button--sign-change">+/-</button>
          <button class="button button--extra button--round">R</button>
          <button class="button button--extra button--square">x²</button>
          <button class="button button--extra button--cube">x³</button>
          <button class="button button--extra button--root">√</button>
          <button class="button button--fraction">🪄</button>
          <button class="button button--extra button--left-bracket">(</button>
          <button class="button button--extra button--right-bracket">)</button>
          <button class="button button--extra button--memory-one">M</button>
          <button class="button button--extra button--memory-two">CM</button>
        </div>
      </div>
    </div>
    <script type="module" src="/src/main.ts"></script>
  </body>
</html>
```

- Your styles, are also messy and need some work I will refactor them and add the code snippet below, this will be using the BEM class names from the HTML in the file above.
  - Try to keep your scss selectors in a similar order to your HTML structure.
  - Have your ELEMENTS nested inside the BLOCK
  - It should only either be a `BLOCK, BLOCK__ELEMENT, BLOCK--MODIFIER, BLOCK__ELEMENT--MODIFIER` . You want to avoid nesting your styles too deeply.

```scss
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  overflow-y: hidden;
}

body {
  margin: 0;
  height: 100vh;
  background-image: url("./calculator-background-2.jpg");
  animation: scrollBackground 30s linear infinite;
}

.title {
  padding-top: 2rem;
  max-width: 50%;
  margin: 0 auto;
  color: rgb(167, 216, 51);
  text-align: center;
  font-size: 2rem;
  font-family: "Orbitron", sans-serif;
  text-shadow: 2px 2px 100px yellow, -2px -2px 100px yellow;
  text-shadow: 2px 2px 114px red, -2px -2px 114px red;
  text-shadow: 4px 4px 102px orange -4px -4px 102px orange;
}

.calculator {
  margin: 0 auto;
  position: absolute;
  padding-left: 0.2rem;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  background-color: black;
  border: 3px solid rgb(138, 130, 17);
  box-shadow: 0 0 80px #fff;

  &__display {
    padding-right: 1rem;
    border: none;
    box-shadow: none;
    width: 300px;
    height: 90px;
    background-color: black;
  }

  &__display-text {
    outline: none;
    background-color: black;
    height: 100%;
    width: 100%;
    border: none;
    color: white;
    font-size: 60px;
    caret-color: transparent;
    text-align: right;

    &--second {
      display: none;
    }
  }

  &__primary-buttons {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 10px;
    padding: 10px;
    padding-bottom: 3rem;
    padding-top: 10px;
  }

  &__secondary-buttons {
    display: none;
  }
}

.disable {
  pointer-events: none;
}

.button {
  font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
  width: 58px;
  height: 58px;
  border-radius: 50%;
  border: none;
  background-color: rgb(57, 52, 52);
  font-size: 2rem;
  color: rgb(245, 245, 226);

  &--fraction {
    background-color: fuchsia;
  }

  &--grey {
    color: black;
    background-color: rgb(149, 146, 146);
  }

  &--orange {
    background-color: rgb(250, 141, 39);
  }

  &--double-zero {
    grid-column: span 2;
    border-radius: 30px;
    width: 100%;
  }
}

@keyframes scrollBackground {
  from {
    background-position: 100% 0;
  }
  to {
    background-position: 0% 0;
  }
}

@media screen and (min-width: 768px) {
  .title {
    margin-bottom: 3rem;
    font-size: 3.5rem;
  }

  .calculator {
    margin-top: 4rem;
    top: 460px;
    height: 630px;

    &__display {
      width: 370px;
      height: 160px;
    }

    &__display-text {
      height: 60%;

      &--second {
        display: unset;
        outline: none;
        background-color: black;
        height: 40%;
        width: 100%;
        font-weight: 400;
        padding: 0;
        margin: 0 auto;
        border: none;
        color: white;
        font-size: 40px;
        caret-color: transparent;
        text-align: right;
      }
    }
  }

  .button {
    width: 80px;
    height: 80px;
    font-size: 2.5rem;

    &--double-zero {
      border-radius: 39px;
      width: 100%;
    }
  }
}

@media screen and (min-width: 1024px) {
  .title {
    padding: 0;
    margin-top: 2rem;
  }

  .calculator {
    height: 600px;
    width: 400px;
  }

  .button {
    width: 75px;
    height: 75px;

    &--double-zero {
      border-radius: 40px;
      width: 100%;
    }
  }
}

@media screen and (min-width: 1366px) {
  .calculator {
    height: 555px;
    width: 480px;
    margin-top: 1rem;

    &__display {
      width: 460px;
    }

    &__buttons-container {
      display: flex;
    }

    &__secondary-buttons {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 10px;
      padding: 10px;
      padding-bottom: 3rem;
      padding-top: 10px;
    }
  }

  .button {
    width: 65px;
    height: 65px;

    &--double-zero {
      width: 100%;
    }

    &--fraction {
      background-color: rgb(82, 207, 82);
    }

    &--extra {
      display: unset;
      background-color: rgb(82, 113, 82);
      font-size: 35px;
    }
  }
}
@media screen and (max-width: 375px) {
  .title {
    padding-top: 1rem;
  }

  .calculator {
    top: 370px;
    height: 450px;
  }
}
```

#### Positive

- You have a functioning calculator! This is A great accomplishment, good going!
- I can see a solid understanding of some of the concepts we have covered so far.
  - You are interacting with the DOM. Displaying and updating values, acting on different events & using logic to get your calculations on the page. :)
- You have the core functionality down and have started looking into the edge cases and additional functionality which is a good place to be.

- The code is well-structured, with clear separation of concerns between functions.

  - Functions are defined for specific tasks, which enhances readability and makes reviewing it easier.

- The `handleWand` function is a fun feature, I like that you have used your knowledge of rgb values to by randomly change the background color based on a random set of numbers you generate.

#### Constructive

- You have a bug atm if multiple operators are pressed as you do not set your operator variable booleans back to false. If I click 5 - 5 click equals and then try to + 5 it will give me -5.

```typescript
const handleEquals = () => {
  if (minusPressed) {
    result = numberOne - Number(display.value);
    display.value = result.toString();
    numberOne = 0;
  }
  if (plusPressed) {
    result = numberOne + Number(display.value);
    display.value = result.toString();
    numberOne = 0;
  }
  if (dividePressed) {
    result = numberOne / Number(display.value);
    display.value = result.toString();
    numberOne = 0;
  }
  if (timesPressed) {
    result = numberOne * Number(display.value);
    display.value = result.toString();
    numberOne = 0;
  }
  buttonsToDisable.forEach(el => {
    el.classList.remove("disable");
  });
  // minusPressed, plusPressed, dividePressed, timesPressed COULD STILL BE TRUE
};

// COULD BE
const handleEquals = () => {
  if (minusPressed) {
    result = numberOne - Number(display.value);
    // SET THE OPERATOR BOOLEAN BACK TO FALSE
    minusPressed = false;
  } else if (plusPressed) {
    result = numberOne + Number(display.value);
    plusPressed = false;
  } else if (dividePressed) {
    result = numberOne / Number(display.value);
    dividePressed = false;
  } else if (timesPressed) {
    result = numberOne * Number(display.value);
    timesPressed = false;
  }
  // MOVE THE CODE YOU DO IN EACH IF BLOCK OUTSIDE SO YOU DO NOT HAVE TO REPEAT IT
  display.value = result.toString();
  numberOne = 0;

  buttonsToDisable.forEach(el => el.classList.remove("disable"));
};
```

- With `handleClickClear` you call `location.reload();` at the very end of the function, this will reload your page and re-run you TS code so you can remove the code before it.

```typescript
const handleClickClear = () => {
  location.reload();
};
```

---
